### ISSUE TITLE
Add notes and reminders to seed data?

### ISSUE THREAD

**Issue by lindsayreiner** [lindsayreiner/pocketRM#68]

**Comment by jordandub1** [comment]
@lindsayreiner is there something specific that needs done to seeds? we fixed the issue last night w Carl I believe and the seeds are working for me

**Comment by lindsayreiner** [comment]
@jordandub1 Ok cool! I wasn't sure if all 15 of the contacts were seeding properly/if they needed edits. My only other thought is to get a few reminders and notes seeded into at least the contact that will be demoed? Thoughts?

**Comment by lindsayreiner** [comment]
I changed the title and label to reflect the above but we could always just let whomever demos add them live.

**Comment by jordandub1** [comment]
I'm cool with adding seeds for notes and reminders

**Comment by lindsayreiner** [comment]
future dev
